project:
  type: book

book:
  title: "Information Systems for Librarians and Information Professionals"
  author: "LIS 260"
  date: "01/19/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap8.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

